import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

import Header from '@/components/Header/Header'
import './globals.css'

const poppins = Poppins({
	subsets: ['latin'],
	weight: ['400', '700'],
	variable: '--font-poppins',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body
				className={`${poppins.className} ${poppins.variable}`}
				suppressHydrationWarning
			>
				<Header />
				{children}
				{/* <Footer /> */}
			</body>
		</html>
	)
}
